### ISSUE TITLE
hero banner does not appear in the application deployment

### ISSUE THREAD

**Issue by matheralvs** [JaleelB/metawizard#1]
@JaleelB, the hero banner is not included in the application, so the image was broken when deployed. Below is a screenshot:

![image](https://github.com/JaleelB/metawizard/assets/109676973/a2db7573-d5c6-4de5-a4fb-3664240c5242)

**Comment by matheralvs** [comment]
Fixed. 🚀

**Comment by JaleelB** [comment]
> Fixed. 🚀

Thank you for pointing it out.
